### ISSUE TITLE
编译错误 Makefile:60: *** Download/default is missing the FILE field..  Stop.

### ISSUE THREAD

**Issue by upupxjg** [AlexZhuo/openwrt-dnsforwarder#2]
make package/dnsforwarder/compile V=99|grep Error
tmp/.config-package.in:7 : warning: ignoring type redefinition of 'PACKAGE_dnsmasq' from 'boolean' to 'tristate'
Makefile:60: *** Download/default is missing the FILE field..  Stop.
make[1]: *** [package/dnsforwarder/compile] Error 2
make: *** [package/dnsforwarder/compile] Error 2

**Comment by chihoutam** [comment]
一样..

**Comment by chihoutam** [comment]
换用LEDE 编译成功....

**Comment by upupxjg** [comment]
不能因噎废食

**Comment by also1412** [comment]
换用LEDE SDK是一种解决方案。

或者，一定要用OpenWrt SDK的话，在出错的Makefile里加入`PKG_SOURCE:=$(PKG_NAME)-$(PKG_VERSION).tar.xz`

**Comment by Iy204** [comment]
还需要在
DEPENDS:=+wget +ipset +dnsmasq-full **+libpthread**
加入加粗的部分。

**Comment by Aslin-Ameng** [comment]
@Iy204  你好朋友请问下如何把LEDE中的kmod-sched-cake也就是LEDE的最新sqm的这个cake模式弄到openwrt里面有朋友说直接复制过去就行但是复制过去编译就报错 一开始复制过去在make menuconfig里面都找不到这个kmod-sched-cake后来有朋友让修改里面的一个这个Makefile文件把DEPENDS:=+kmod-ipt-conntrack @!LINUX_3_18  改为  DEPENDS:=+kmod-ipt-conntrack就找到了 不过还是报错 报错信息如下

SHELL= /home/xmc/openwrt/staging_dir/host/bin/flock /home/xmc/openwrt/tmp/.root-copy.flock -c 'cp -fpR /home/xmc/openwrt/staging_dir/target-mips_34kc_uClibc-0.9.33.2/root-ar71xx/tmp-kmod-gpio-button-hotplug/. /home/xmc/openwrt/staging_dir/target-mips_34kc_uClibc-0.9.33.2/root-ar71xx/'
rm -rf /home/xmc/openwrt/staging_dir/target-mips_34kc_uClibc-0.9.33.2/root-ar71xx/tmp-kmod-gpio-button-hotplug
touch /home/xmc/openwrt/staging_dir/target-mips_34kc_uClibc-0.9.33.2/root-ar71xx/stamp/.kmod-gpio-button-hotplug_installed
if [ -f /home/xmc/openwrt/staging_dir/target-mips_34kc_uClibc-0.9.33.2/pkginfo/gpio-button-hotplug.default.install.clean ]; then rm -f /home/xmc/openwrt/staging_dir/target-mips_34kc_uClibc-0.9.33.2/pkginfo/gpio-button-hotplug.default.install /home/xmc/openwrt/staging_dir/target-mips_34kc_uClibc-0.9.33.2/pkginfo/gpio-button-hotplug.default.install.clean; fi; echo "kmod-gpio-button-hotplug" >> /home/xmc/openwrt/staging_dir/target-mips_34kc_uClibc-0.9.33.2/pkginfo/gpio-button-hotplug.default.install
make[3]: Leaving directory '/home/xmc/openwrt/package/kernel/gpio-button-hotplug'
make[3]: Entering directory '/home/xmc/openwrt/package/kernel/kmod-sched-cake'
Makefile:43: *** Download/default is missing the SUBDIR field..  Stop.
make[3]: Leaving directory '/home/xmc/openwrt/package/kernel/kmod-sched-cake'
package/Makefile:191: recipe for target 'package/kernel/kmod-sched-cake/compile' failed
make[2]: *** [package/kernel/kmod-sched-cake/compile] Error 2
make[2]: Leaving directory '/home/xmc/openwrt'
package/Makefile:188: recipe for target '/home/xmc/openwrt/staging_dir/target-mips_34kc_uClibc-0.9.33.2/stamp/.package_compile' failed
make[1]: *** [/home/xmc/openwrt/staging_dir/target-mips_34kc_uClibc-0.9.33.2/stamp/.package_compile] Error 2
make[1]: Leaving directory '/home/xmc/openwrt'
/home/xmc/openwrt/include/toplevel.mk:181: recipe for target 'world' failed
make: *** [world] Error 2

有的朋友说照着openwrt的Makefile改可是一点不会改  哎  能不能朋友看看是怎么回事呢
