### ISSUE TITLE
反馈问题

### ISSUE THREAD

**Issue by RoweV194** [AlexZhuo/openwrt-dnsforwarder#9]
![qq 20180205143359](https://user-images.githubusercontent.com/27860403/35791233-bca27b3c-0a81-11e8-8c3e-1dd229985acf.png)
16.04编译成功
17.10.1 输入 make && sudo make install 时遇到以上问题
不知道作者是否打算在新的Ubuntu上支持，还是打算长期支持16.04

**Comment by Cathgao** [comment]
请问如何解决？

**Comment by RoweV194** [comment]
> 请问如何解决？

当时的解决办法就是用回16.04

不过我已经差不多1年没编译过了，现在有没有这问题我不清楚。
